name: 'Run Tests'

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.can-fail }}
    strategy:
      fail-fast: true
      matrix:
        php: ['8.1', '8.2', '8.3']
        symfony: ['5.4.*', '6.3.*', '6.4.*']
        composer-flags: ['--prefer-stable']
        can-fail: [false]
        has-mongodb: [true]
        extensions: ['curl, iconv, mbstring, mongodb, pdo, pdo_sqlite, sqlite, zip']
        include:
          - php: '8.1'
            symfony: '5.4.*'
            composer-flags: '--prefer-stable --prefer-lowest'
            extensions: 'curl, iconv, mbstring, mongodb, pdo, pdo_sqlite, sqlite, zip'
            can-fail: false
            has-mongodb: true
          - php: '8.3'
            symfony: '7.0.*'
            composer-flags: '--prefer-stable --prefer-lowest'
            extensions: 'curl, iconv, mbstring, pdo, pdo_sqlite, sqlite, zip'
            can-fail: false
            has-mongodb: false
        exclude:
          - php: '8.1'
            symfony: '7.0.*'

    name: "PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}${{ matrix.composer-flags != '' && format(' - Composer {0}', matrix.composer-flags) || '' }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2,flex
          extensions: ${{ matrix.extensions }}
          coverage: none

      - name: Remove MongoDB
        if: matrix.has-mongodb == false
        run: |
          composer remove --dev --no-update doctrine/mongodb-odm doctrine/mongodb-odm-bundle

      - name: Install dependencies
        run: |
          composer update ${{ matrix.composer-flags }} --prefer-dist --no-suggest
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}

      - name: Execute tests
        run: vendor/bin/phpunit
